# 代理模型
resnet18:
 full_name: resnet18
#  ckp_path: resnet18_cifar10.pth
#  ckp_path: resnet18_cifar10_20.pth
#  ckp_path: resnet18_cifar10_norm.pth
#  ckp_path: resnet18_cifar10_aug2.pth # pre
#  ckp_path: resnet18_cifar10_org.pth
 ckp_path: resnet18.pth.tar

inc_v3:
 full_name: inception_v3
#  ckp_path: inception_v3_cifar10.pth
#  ckp_path: inception_v3_cifar10_20.pth
#  ckp_path: inception_v3_cifar10_norm.pth
#  ckp_path: inception_v3_cifar10_aug2.pth # pre
#  ckp_path: inception_v3_cifar10_org.pth
 ckp_path: inception_v3.pth.tar

vit_t:
 full_name: vit_tiny_patch16_224
#  ckp_path: vit_tiny_patch16_224_cifar10.pth
#  ckp_path: vit_tiny_patch16_224_cifar10_20.pth
#  ckp_path: vit_tiny_patch16_224_cifar10_norm.pth
#  ckp_path: vit_tiny_patch16_224_cifar10_aug2.pth # pre
#  ckp_path: vit_tiny_patch16_224_cifar10_org.pth
 ckp_path: vit_tiny.pth.tar

deit_t:
 full_name: deit_tiny_patch16_224
#  ckp_path: deit_tiny_patch16_224_cifar10.pth
#  ckp_path: deit_tiny_patch16_224_cifar10_20.pth
#  ckp_path: deit_tiny_patch16_224_cifar10_norm.pth
#  ckp_path: deit_tiny_patch16_224_cifar10_aug2.pth # pre
#  ckp_path: deit_tiny_patch16_224_cifar10_org.pth
 ckp_path: deit_tiny.pth.tar


# 目标模型
resnet50:
 full_name: resnet50
 ckp_path: resnet50.pth.tar

wrn101_2:
 full_name: wide_resnet101_2
 ckp_path: wide_resnet101_2.pth.tar

bit50_1:
 full_name: resnetv2_50x1_bit.goog_in21k_ft_in1k
 ckp_path: resnetv2_50x1_bitm.pth.tar
#  ckp_path: resnetv2_50x1_bit_cifar10.pth

bit101_1:
 full_name: resnetv2_101x1_bit.goog_in21k_ft_in1k
 ckp_path: resnetv2_101x1_bitm.pth.tar

vit_b:
 full_name: vit_base_patch16_224
 ckp_path: vit_base.pth.tar

deit_b:
 full_name: deit_base_patch16_224
 ckp_path: deit_base.pth.tar

swin_b:
 full_name: swin_base_patch4_window7_224
#  ckp_path: swin_base.pth.tar
 ckp_path: swin_base_patch4_window7_224_cifar10.pth

swin_s:
 full_name: swin_small_patch4_window7_224
#  ckp_path: swin_small.pth.tar
 ckp_path: swin_small_patch4_window7_224_cifar10.pth